-- -- Búsqueda de productos por nombre y por categoría.
CREATE OR REPLACE FUNCTION FIND_PRODUCT_BY_NAME_AND_CATEGORY (IN P_NAME VARCHAR(40), IN C_NAME VARCHAR(25)) 
RETURNS TABLE (ID INTEGER, CATEGORY_ID INTEGER, NAME VARCHAR, PRICE DECIMAL) 
AS $$
BEGIN
	RETURN QUERY
	SELECT P.ID, P.CATEGORY_ID,P.NAME, P.PRICE
	FROM PRODUCTS P
	JOIN CATEGORIES C ON P.CATEGORY_ID = C.ID
	WHERE P.NAME = P_NAME
	AND C.NAME = C_NAME;
END;
$$ LANGUAGE PLPGSQL;

SELECT ID, CATEGORY_ID, NAME, PRICE
FROM FIND_PRODUCT_BY_NAME_AND_CATEGORY ('Parka invierno', 'Ropa');

-- Top N productos por ventas (cantidad o monto).
-- Ventas por mes y por categoría (sumas y conteos).
-- Ventas por mes y por categoría (sumas y conteos).
SELECT
	TO_CHAR(P.PAYDAY, 'YYYY-MM') AS MONTH,
	C.NAME AS CATEGORY,
	SUM(OI.QUANTITY * OI.PRICE) AS TOTAL,
	-- QUANTITY SE REFIERE A LA CANTIDAD DE ORDERS_ITEM, SI SE QUISIERA
	-- CALCULAR EL TOTAL DE PRODUCTOS VENDIDOS HABRÍA QUE CAMBIARLO POR SUM
	COUNT(OI.QUANTITY) AS QUANTITY
FROM
	ORDERS O
	JOIN PAYMENTS P ON P.ID = O.PAYMENT_ID
	JOIN ORDERS_ITEM OI ON OI.ORDER_ID = O.ID
	JOIN PRODUCTS ON PRODUCTS.ID = OI.PRODUCT_ID
	JOIN CATEGORIES C ON PRODUCTS.CATEGORY_ID = C.ID
WHERE
	P.PAID = TRUE
GROUP BY
	TO_CHAR(P.PAYDAY, 'YYYY-MM'),
	C.NAME
	
-- Ticket promedio en rango de fechas.
-- Stock bajo (umbral configurable)
CREATE OR REPLACE FUNCTION PRODUCTS_WITH_LOW_STOCK (IN THRESHOLD INTEGER)
RETURNS TABLE (NAME VARCHAR, QUANTITY INTEGER)
AS $$
BEGIN
	RETURN QUERY 
	SELECT P.NAME, I.QUANTITY
	FROM PRODUCTS P
	JOIN INVENTORY I ON P.ID = I.PRODUCT_ID
	WHERE I.QUANTITY <= THRESHOLD;
END;
$$ LANGUAGE PLPGSQL;

SELECT NAME, QUANTITY FROM PRODUCTS_WITH_LOW_STOCK(19);

-- Productos sin ventas.
SELECT
	P.ID,
	P.CATEGORY_ID,
	P.NAME,
	P.PRICE
FROM
	PRODUCTS P
	LEFT JOIN (
		-- excluir productos con ventas
		SELECT DISTINCT
			OI.PRODUCT_ID
		FROM
			ORDERS_ITEM OI
			JOIN ORDERS O ON OI.ORDER_ID = O.ID
			JOIN PAYMENTS PAY ON O.PAYMENT_ID = PAY.ID
		WHERE
			PAY.PAID = TRUE
	) AS V ON P.ID = V.PRODUCT_ID
WHERE
	V.PRODUCT_ID IS NULL;
    
-- Clientes frecuentes (≥ X órdenes).
CREATE OR REPLACE FUNCTION FREQUENT_CUSTOMERS(IN O_NUMBER INTEGER)
RETURNS TABLE (ID INTEGER, NAME VARCHAR, QUANTITY BIGINT)
AS $$
BEGIN
	RETURN QUERY 
	SELECT C.ID, C.NAME, COUNT (C.ID) AS QUANTITY
	FROM CUSTOMERS C
	JOIN ORDERS O ON O.CUSTOMER_ID = C.ID
	GROUP BY C.ID
	HAVING COUNT (C.ID) >= O_NUMBER;
END;
$$ LANGUAGE PLPGSQL;

SELECT ID, NAME, QUANTITY FROM FREQUENT_CUSTOMERS(2);
-- Cualquier consulta que estime relevante para su proyecto.
