-- PARA POSTGRESQL
CREATE TYPE PAY_METHOD AS ENUM('CASH', 'CARD');

CREATE TABLE CUSTOMERS (
	ID SERIAL,
	NAME VARCHAR(50),
	RUT VARCHAR(12) UNIQUE NOT NULL,
	EMAIL VARCHAR(50) UNIQUE NOT NULL,
	CELLPHONE VARCHAR(12) NOT NULL,
	-- LA CONTRASEÑA DEBERÍA SER UN HASH
	PASS_HASH VARCHAR NOT NULL,
	CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID)
);

CREATE TABLE PAYMENTS (
	ID SERIAL,
	METHOD PAY_METHOD NOT NULL,
	PAYDAY TIMESTAMP NOT NULL,
	PAID BOOLEAN NOT NULL,
	CONSTRAINT PK_PAYMENTS PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
	ID SERIAL,
	CUSTOMER_ID INTEGER,
	PAYMENT_ID INTEGER,
	CREATION_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	TOTAL DECIMAL CHECK (TOTAL > 0.0),
	CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
	CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID) ON DELETE CASCADE,
	CONSTRAINT FK_ORDERS_PAYMENTS FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID)
);

CREATE TABLE CATEGORIES (
	ID SERIAL,
	NAME VARCHAR(25) NOT NULL,
	CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS (
	ID SERIAL,
	CATEGORY_ID INTEGER,
	NAME VARCHAR(40) NOT NULL,
	PRICE DECIMAL NOT NULL CHECK (PRICE > 0.0),
	CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCTS_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID)
);

CREATE TABLE INVENTORY (
	ID SERIAL,
	PRODUCT_ID INTEGER UNIQUE,
	QUANTITY INTEGER NOT NULL CHECK (QUANTITY >= 0),
	CONSTRAINT PK_INVENTORY PRIMARY KEY (ID),
	CONSTRAINT FK_INVENTORY_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID) ON DELETE CASCADE
);

CREATE TABLE ORDERS_ITEM (
	ID SERIAL,
	ORDER_ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	PRICE DECIMAL NOT NULL CHECK (PRICE > 0.0),
	QUANTITY INTEGER NOT NULL CHECK (QUANTITY > 0),
	SUB_TOTAL DECIMAL GENERATED ALWAYS AS (PRICE * QUANTITY) STORED,
	CONSTRAINT PK_ORDERS_ITEM PRIMARY KEY (ID),
	CONSTRAINT FK_ORDERS_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE,
	CONSTRAINT FK_ORDERS_ITEM_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);

CREATE INDEX IDX_PRODUCTS_NAME ON PRODUCTS (NAME);

CREATE INDEX IDX_INVENTORY_QUANTITY ON INVENTORY (QUANTITY);